# Generated by Django 3.2.3 on 2021-06-22 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='blue_votes',
            field=models.ManyToManyField(related_name='bluevotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fight',
            name='red_votes',
            field=models.ManyToManyField(related_name='redvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
